/*
 * This file is generated by jOOQ.
 */
package elfak.teodora.elastic.jooq.model;


import elfak.teodora.elastic.jooq.model.tables.User;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.User</code>.
     */
    public static final User USER = User.USER;
}
